apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sunbird
  name: public-key-service
  labels:
    app: public-key-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: public-key-service
  template:
    metadata:
      name: public-key-service
      labels:
        app: public-key-service
    spec:
      containers:
        - name: public-key-service
          image: dockerhub/sunbird-rc-public-key-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3300
          env:
            - name: CONFIG_BASE_PATH
              value: /etc/keys
      restartPolicy: Always
